export type DepositType = 'PERCENT' | 'FIXED';
export type PaymentMode = 'NONE' | 'FULL' | 'DEPOSIT';

export type AssetStatus = 'AVAILABLE' | 'RESERVED' | 'RENTED' | 'MAINTENANCE' | 'INACTIVE';
export type ReservationStatus = 'CONFIRMED' | 'RENTED' | 'RETURNED' | 'CANCELLED' | 'COMPLETED' | 'ERROR';
export type WorkflowStage = 'RESERVATION' | 'QUOTE' | 'CONTRACT' | 'INVOICE' | 'PAYMENT' | 'READY' | 'RENTED' | 'RETURNED' | 'COMPLETED';
export type DocumentType = 'QUOTE' | 'CONTRACT' | 'INVOICE';
export type PaymentType = 'PAYMENT' | 'BOOKING_DEPOSIT' | 'SECURITY_DEPOSIT' | 'REFUND' | 'DEPOSIT_REFUND' | 'DAMAGE_CHARGE';
export type InspectionType = 'DEPARTURE' | 'RETURN';

export type Asset = {
  _id?: string;
  title?: string;
  assetNumber?: string;
  productType?: string;
  categoryId?: string;
  categoryName?: string;
  catalogTagsJson?: string;
  status?: AssetStatus;
  dailyRateCents?: number;
  weeklyRateCents?: number;
  monthlyRateCents?: number;
  discountAfterDays?: number;
  discountPercent?: number;
  currency?: string;
  serialNumber?: string;
  image?: unknown;
  notes?: string;
  active?: boolean;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type Category = {
  _id?: string;
  name?: string;
  key?: string;
  description?: string;
  active?: boolean;
  forEquipment?: boolean;
  forProducts?: boolean;
  forExtras?: boolean;
  sortOrder?: number;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type Customer = {
  _id?: string;
  customerNumber?: string;
  firstName?: string;
  lastName?: string;
  companyName?: string;
  email?: string;
  phone?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  region?: string;
  postalCode?: string;
  country?: string;
  discountPercent?: number;
  notes?: string;
  active?: boolean;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type AppSettings = {
  _id?: string;
  settingsKey?: string;
  companyName?: string;
  logoUrl?: string;
  bookingThemeJson?: string;
  bookingHeroTitle?: string;
  bookingHeroSubtitle?: string;
  bookingHeroBackgroundUrl?: string;
  currency?: string;
  defaultBufferBeforeHours?: number;
  defaultBufferAfterHours?: number;
  taxesEnabled?: boolean;
  tax1Name?: string;
  tax1Rate?: number;
  tax2Name?: string;
  tax2Rate?: number;
  tax2Compound?: boolean;
  defaultDepositEnabled?: boolean;
  defaultDepositType?: DepositType;
  defaultDepositValue?: number;
  defaultQuoteTemplateId?: string;
  defaultContractTemplateId?: string;
  defaultInvoiceTemplateId?: string;
  paymentProvider?: string;
  payflowProvider?: string;
  payflowEnvironment?: string;
  payflowAccountId?: string;
  payflowAccountStatus?: string;
  payflowDetailsSubmitted?: boolean;
  payflowChargesEnabled?: boolean;
  payflowPayoutsEnabled?: boolean;
  payflowRequirementsCurrentlyDueJson?: string;
  payflowRequirementsPastDueJson?: string;
  payflowRequirementsPendingVerificationJson?: string;
  payflowCountry?: string;
  payflowDefaultCurrency?: string;
  payflowLastSyncedAt?: Date | string | null;
  active?: boolean;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type DocumentTemplate = {
  _id?: string;
  name?: string;
  documentType?: DocumentType;
  logoUrl?: string;
  titleText?: string;
  introText?: string;
  termsText?: string;
  footerText?: string;
  requiredFieldsCsv?: string;
  active?: boolean;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type Reservation = {
  _id?: string;
  reservationNumber?: string;
  customerId?: string;
  customerNumber?: string;
  customerName?: string;
  customerEmail?: string;
  customerPhone?: string;
  customerAddressLine1?: string;
  customerAddressLine2?: string;
  customerCity?: string;
  customerRegion?: string;
  customerPostalCode?: string;
  customerCountry?: string;
  startDateTime?: Date | string;
  endDateTime?: Date | string;
  bufferBeforeHours?: number;
  bufferAfterHours?: number;
  status?: ReservationStatus;
  workflowStage?: WorkflowStage;
  quoteTemplateId?: string;
  quoteTemplateName?: string;
  contractTemplateId?: string;
  contractTemplateName?: string;
  invoiceTemplateId?: string;
  invoiceTemplateName?: string;
  subtotalCents?: number;
  customerDiscountPercent?: number;
  discountCents?: number;
  preTaxTotalCents?: number;
  tax1Name?: string;
  tax1Rate?: number;
  tax1Cents?: number;
  tax2Name?: string;
  tax2Rate?: number;
  tax2Cents?: number;
  taxTotalCents?: number;
  totalCents?: number;
  currency?: string;
  depositRequired?: boolean;
  depositType?: DepositType;
  depositValue?: number;
  depositAmountCents?: number;
  amountDueNowCents?: number;
  balanceDueCents?: number;
  paymentMode?: PaymentMode;
  checkoutDateTime?: Date | string;
  returnDateTime?: Date | string;
  closedDateTime?: Date | string;
  notes?: string;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type ReservationItem = {
  _id?: string;
  reservationId?: string;
  reservationNumber?: string;
  lineType?: 'RENTAL' | 'PRODUCT' | 'ADDON' | 'SERVICE';
  assetId?: string;
  assetNumber?: string;
  assetTitle?: string;
  catalogItemId?: string;
  catalogItemType?: 'PRODUCT' | 'ADDON' | 'SERVICE';
  itemName?: string;
  sku?: string;
  quantity?: number;
  unitPriceCents?: number;
  taxable?: boolean;
  startDateTime?: Date | string;
  endDateTime?: Date | string;
  blockedStartDateTime?: Date | string;
  blockedEndDateTime?: Date | string;
  bufferBeforeHours?: number;
  bufferAfterHours?: number;
  billableDays?: number;
  lineTotalCents?: number;
  pricingMode?: string;
  currency?: string;
  status?: ReservationStatus;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type RentalDocument = {
  _id?: string;
  reservationId?: string;
  reservationNumber?: string;
  documentNumber?: string;
  documentType?: DocumentType;
  status?: string;
  templateId?: string;
  templateName?: string;
  logoUrl?: string;
  titleText?: string;
  introText?: string;
  termsText?: string;
  footerText?: string;
  requiredFieldsCsv?: string;
  snapshotJson?: string;
  subtotalCents?: number;
  discountCents?: number;
  preTaxTotalCents?: number;
  tax1Name?: string;
  tax1Cents?: number;
  tax2Name?: string;
  tax2Cents?: number;
  amountCents?: number;
  currency?: string;
  issuedDate?: Date | string;
  sentDate?: Date | string;
  acceptedDate?: Date | string;
  signedDate?: Date | string;
  dueDate?: Date | string;
  signerName?: string;
  pdfUrl?: string;
  notes?: string;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type Payment = {
  _id?: string;
  reservationId?: string;
  reservationNumber?: string;
  paymentNumber?: string;
  paymentType?: PaymentType;
  method?: string;
  status?: string;
  amountCents?: number;
  currency?: string;
  paymentDate?: Date | string;
  reference?: string;
  provider?: string;
  providerEnvironment?: string;
  providerAccountId?: string;
  providerPaymentId?: string;
  providerChargeId?: string;
  providerRefundId?: string;
  wixPaymentLinkId?: string;
  wixPaymentUrl?: string;
  wixCheckoutId?: string;
  wixOrderId?: string;
  wixTransactionId?: string;
  wixOnlinePayment?: boolean;
  remainingBalanceCents?: number;
  notes?: string;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type Inspection = {
  _id?: string;
  reservationId?: string;
  reservationNumber?: string;
  inspectionNumber?: string;
  inspectionType?: InspectionType;
  status?: string;
  assetId?: string;
  assetNumber?: string;
  assetTitle?: string;
  condition?: string;
  hasDamage?: boolean;
  damageDescription?: string;
  damageAmountCents?: number;
  photoUrls?: string;
  signerName?: string;
  inspectionDate?: Date | string;
  notes?: string;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type ActivityEntry = {
  _id?: string;
  reservationId?: string;
  reservationNumber?: string;
  actionType?: string;
  description?: string;
  actor?: string;
  eventDate?: Date | string;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type BookingLock = {
  _id?: string;
  assetId?: string;
  lockToken?: string;
  expiresAt?: Date | string;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};

export type CatalogStockLock = {
  _id?: string;
  catalogItemId?: string;
  lockToken?: string;
  expiresAt?: Date | string;
  _createdDate?: Date | string;
  _updatedDate?: Date | string;
};
