import type { DataCollection } from '@wix/astro/builders';

export const collectionIdSuffix = 'reservations';

export default {
  idSuffix: collectionIdSuffix,
  displayName: 'RentalFlow - Reservations',
  fields: [
    { type: 'TEXT', displayName: 'Numéro de réservation', key: 'reservationNumber' },
    { type: 'TEXT', displayName: 'ID client', key: 'customerId' },
    { type: 'TEXT', displayName: 'Numéro client', key: 'customerNumber' },
    { type: 'TEXT', displayName: 'Client', key: 'customerName' },
    { type: 'TEXT', displayName: 'Courriel', key: 'customerEmail' },
    { type: 'TEXT', displayName: 'Téléphone', key: 'customerPhone' },
    { type: 'TEXT', displayName: 'Adresse client', key: 'customerAddressLine1' },
    { type: 'TEXT', displayName: 'Adresse client 2', key: 'customerAddressLine2' },
    { type: 'TEXT', displayName: 'Ville client', key: 'customerCity' },
    { type: 'TEXT', displayName: 'Province / État client', key: 'customerRegion' },
    { type: 'TEXT', displayName: 'Code postal client', key: 'customerPostalCode' },
    { type: 'TEXT', displayName: 'Pays client', key: 'customerCountry' },
    { type: 'DATETIME', displayName: 'Début de location', key: 'startDateTime' },
    { type: 'DATETIME', displayName: 'Fin de location', key: 'endDateTime' },
    { type: 'NUMBER', displayName: 'Buffer avant en heures', key: 'bufferBeforeHours' },
    { type: 'NUMBER', displayName: 'Buffer après en heures', key: 'bufferAfterHours' },
    { type: 'TEXT', displayName: 'Statut', key: 'status' },
    { type: 'TEXT', displayName: 'Étape du flux', key: 'workflowStage' },
    { type: 'TEXT', displayName: 'Modèle devis ID', key: 'quoteTemplateId' },
    { type: 'TEXT', displayName: 'Modèle devis', key: 'quoteTemplateName' },
    { type: 'TEXT', displayName: 'Modèle contrat ID', key: 'contractTemplateId' },
    { type: 'TEXT', displayName: 'Modèle contrat', key: 'contractTemplateName' },
    { type: 'TEXT', displayName: 'Modèle facture ID', key: 'invoiceTemplateId' },
    { type: 'TEXT', displayName: 'Modèle facture', key: 'invoiceTemplateName' },
    { type: 'NUMBER', displayName: 'Sous-total en cents', key: 'subtotalCents' },
    { type: 'NUMBER', displayName: 'Rabais client en pourcentage', key: 'customerDiscountPercent' },
    { type: 'NUMBER', displayName: 'Rabais client en cents', key: 'discountCents' },
    { type: 'NUMBER', displayName: 'Total avant taxes en cents', key: 'preTaxTotalCents' },
    { type: 'TEXT', displayName: 'Taxe 1 - nom', key: 'tax1Name' },
    { type: 'NUMBER', displayName: 'Taxe 1 - taux (%)', key: 'tax1Rate' },
    { type: 'NUMBER', displayName: 'Taxe 1 en cents', key: 'tax1Cents' },
    { type: 'TEXT', displayName: 'Taxe 2 - nom', key: 'tax2Name' },
    { type: 'NUMBER', displayName: 'Taxe 2 - taux (%)', key: 'tax2Rate' },
    { type: 'NUMBER', displayName: 'Taxe 2 en cents', key: 'tax2Cents' },
    { type: 'NUMBER', displayName: 'Taxes totales en cents', key: 'taxTotalCents' },
    { type: 'NUMBER', displayName: 'Total en cents', key: 'totalCents' },
    { type: 'TEXT', displayName: 'Devise', key: 'currency' },
    { type: 'BOOLEAN', displayName: 'Dépôt requis', key: 'depositRequired' },
    { type: 'TEXT', displayName: 'Type de dépôt', key: 'depositType' },
    { type: 'NUMBER', displayName: 'Valeur du dépôt', key: 'depositValue' },
    { type: 'NUMBER', displayName: 'Montant du dépôt en cents', key: 'depositAmountCents' },
    { type: 'NUMBER', displayName: 'Montant dû maintenant en cents', key: 'amountDueNowCents' },
    { type: 'NUMBER', displayName: 'Solde à payer en cents', key: 'balanceDueCents' },
    { type: 'TEXT', displayName: 'Mode de paiement', key: 'paymentMode' },
    { type: 'DATETIME', displayName: 'Date du départ', key: 'checkoutDateTime' },
    { type: 'DATETIME', displayName: 'Date du retour', key: 'returnDateTime' },
    { type: 'DATETIME', displayName: 'Date de clôture', key: 'closedDateTime' },
    { type: 'TEXT', displayName: 'Notes', key: 'notes' },
  ],
  displayField: 'reservationNumber',
  dataPermissions: {
    itemInsert: 'CMS_EDITOR',
    itemRead: 'CMS_EDITOR',
    itemRemove: 'CMS_EDITOR',
    itemUpdate: 'CMS_EDITOR',
  },
  indexes: [
    {
      fields: [{ path: 'reservationNumber', order: 'ASC' }],
      unique: true,
      caseInsensitive: true,
    },
    {
      fields: [{ path: 'startDateTime', order: 'ASC' }, { path: 'status', order: 'ASC' }],
      unique: false,
      caseInsensitive: false,
    },
    {
      fields: [{ path: 'customerId', order: 'ASC' }, { path: 'startDateTime', order: 'DESC' }],
      unique: false,
      caseInsensitive: false,
    },
  ],
  initialData: [],
} satisfies DataCollection;
